### PR TITLE
api endpoints refactor

### PR DESCRIPTION
**Pull request by asifmu97**
New environment file has been uploaded.
Right now, the authentication endpoint hasn't changed because that hasn't been approved by backend.

### CODE REVIEW

**Review by h-ng — CHANGES_REQUESTED** [review]
I notice you didn't put the whole api path in the env. file but just the very first part of it, could you consider using `REACT_APP_API_USER_LISTS=user/lists` for all of the user's list related apis?

I don't think I could comprehend the idea of having several names for the same value in the env. file while at the end we don't use it well, or please educate me on this 😭.

Another thing I really want to suggest, for the api variables, please group them, reorder alphabetically, and leave a blank line before the group to separate from other authentication vars. It's pretty hard to read right now in the env. file with the number of variables we have and the long names.

**Comment by asifmu97** [comment]
1- endpoints might get refactored and so they should all have their own variable names even if they have the same prefix (for now). If things change in the future, instead of recreating endpoints in the env file, we can simply change them.

2- the slashes missing from some of the endpoints isn't a biggie. Can be fixed in a later ticket.

3- noted. Please feel free to sort the env file as you like from our folder.

**Comment by h-ng** [comment]
I don't mind to cancel this change request and move along because you have once made a point I totally agree, that it's so likely there are future contribution to code very later on, even though this defeats my definition of code review and good practice. 

Yet, I will just continue this discussion as an exchange of thoughts. It's great 🤓.

1 - Why would we worry so much about refactoring when all we are going to ever use these apis are in the one place - Backend.service? This would also answer question of why having constants for api endpoints when we don't need to reuse them at different places. The Backend.service already handle this responsibility.

2 - Right, we can just work with this inconsistency and that's not a real big thing. But if you think you would want to update them, it's better to get it done while you already have an MR open, than referring to another ticket for the same refactoring purpose. Otherwise, I wouldn't come back to change it, or change it as part of other tickets since again, it'll cause conflicts as we had before.

**Comment by asifmu97** [comment]
1- Throughout the course, we've had to change our API endpoints twice. The second time was a much more significant change. Having these endpoints in the env file helped make those refactors easier in both sprints (including this one).
You _are_ right that we're only ever using these endpoints in the services/Backend file and we could just make our changes in that file instead. But that's just one approach vs another. Plus, the other frontend also keeps the endpoints in the env files and so that nudges me towards this approach more. Plus, if my endpoints ever change, I can just pass in a different env file to our Vercel deployment and itll be a much smoother transition there.

2- The "/" is missing only from endpoints that _end_ with the given environment variable. So if there's an endpoint like "user/lists", it is different from 
"user/lists/" since the second one will have something appended to it (such as a parameter) after the slash.
I tried to change them, didn't work. I'm pretty sure it's already set up the way it's supposed to be. The code doesn't append any slashes to our endpoint anywhere either.

**Comment by h-ng** [comment]
1- Ok, so looks like it does have some good benefits.
2- Then, let's not have the trailing slash and add it in the code is what I meant. But not a big thing right now.

Other than those, have tested and works well. Thanks for the great job, Sam! 👏👏👏

**Review by h-ng — APPROVED** [review]

**Comment by asifmu97** [comment]
thank you so much for the great questions! merging now 😄

**Pull request merged**
