### PR TITLE
Sam/com 220 custom ingredients

### PR DESCRIPTION
**Pull request by asifmu97**
This branch has fully implemented Custom Ingredients Feature ( 😥 )
It has the following:

**Logic/DSO changes**
1.Custom Ingredient flag in this Ingredient DSO
2. new List DSO method to accommodate custom ingredients
3. user DSO methods to accommodate custom ingredients
4. services method to accommodate custom ingredients

**UI Changes**
1. `AllIngredients page` now lets the user create a custom ingredient (unique name). The user wont be allowed to create a custom ingredient with the same name as a provided common ingredient
2.  `AllIngredients page` now lets the user filter their ingredient on All, Common, Custom. 
3. `AllIngredients page` now displays an identifier icon for custom ingredient (magic wand wooo)
4. `AllIngredients page` now has a delete button for custom ingredients  (cascade delete preferred in backend)
5. `ListNav page` now lets the user add custom ingredients (with filters)
6. `ListNav page` now also diplays the magic wand on custom ingredients.

Thank you for coming to my TED talk

### CODE REVIEW

**Review by h-ng — CHANGES_REQUESTED** [review]
New feature looks very nice. Good job!

Found 2 issue though:
1. Please change the sentence in confirm delete ingredient in the All Ingredients, cause the "list" could not make sense here.
image

2. There is bug that when you delete a custom ingredient totally in the All Ingredients tab, it still shows in the lists it was added. I tried to navigate away or go to other list and come back but it still won't remove. I had to manually click refresh page to see the update.

**Comment by asifmu97** [comment]
Thank you for the feedback and compliments!

1. I've pushed the change to fix this, thank you for catching it!
2. I believe this might be because you haven't pulled from feature/custom-ingredient since the afternoon. Vaughn was able to implement the cascading delete for us. If you did pull from the branch and the error persisted, please let me know and I'll look into it.

Thanks again~

**Comment by h-ng** [comment]
> Thank you for the feedback and compliments!
> 
> 1. I've pushed the change to fix this, thank you for catching it!
> 2. I believe this might be because you haven't pulled from feature/custom-ingredient since the afternoon. Vaughn was able to implement the cascading delete for us. If you did pull from the branch and the error persisted, please let me know and I'll look into it.
> 
> Thanks again~

The bug is found when I'm testing with mock user so you might want to check that again, please

**Comment by asifmu97** [comment]
Ohhh! You're right I didn't add that logic to the mock. Tysm for the thorough testing. You da 🐐

**Comment by asifmu97** [comment]
Hello! The bug has been fixed. Thanks so much again!

**Review by h-ng — APPROVED** [review]
Works perfectly now

**Pull request merged**
