### PR TITLE
Refactor My Lists page: Upsize texts, improve action button

### PR DESCRIPTION
**Pull request by h-ng**
image

### CODE REVIEW

**Review by asifmu97 — COMMENTED** [review]
Looks rly good, well done! One little note tho:

image

i noticed that once our List.name exceeds 30 characters, the delete buttons get pushed off the screen. Up until "LISTLISTLISTLISTLISTLISTLIST" (21 characters), the delete button still showed. Its only when i added the last entry that the buttons disappeared.
I'm not sure if we should handle this by limiting the List name's length in the backend or if there's a way to deal with this on our frontend?

Please let me know what you think 😄

**Comment by h-ng** [comment]
The text actually wraps when it gets longer as a phrase. In your case, it happens because you are testing one nonbreaking word. I think this is not a realistic case for a word to get bigger than 20 characters. And while it's possible, and makes sense to *us*, to apply the restriction on a single word length on the frontend, when the user input the list name, but I can't imagine reading that restriction as an user. But again, it's a rare case so maybe we still can implement it and only a few weird users would see it.

**Comment by asifmu97** [comment]
Ahh true, I see what you mean. 

So if the user was to make a list called "My fourth Grocery List with lots of stuff" (30+ chars) as a name, would it not replicate that error?

**Comment by h-ng** [comment]
Forgot to attach an image :) 
image

**Comment by asifmu97** [comment]
You're the goat; sounds good! Approving 👏

**Review by asifmu97 — APPROVED** [review]
LGTM! Well done

**Pull request merged**
